apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-java-app
  labels:
    app: argo-java-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argo-java-app
  template:
    metadata:
      labels:
        app: argo-java-app
    spec:
      containers:
      - name: argo-java-app-container
        image: rspgaikwad/argo-java-app:v1.0.2
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
