format_version: 10
pipelines:
  test-pipeline-2:
    group: My-Pipelines
    label_template: "${COUNT}-#{TAG}"
    lock_behavior: none
    parameters:
      TAG: v1.0.0
    materials:
      test-material-2:
        git: https://github.com/rs-pravingaikwad/argo-java-app-k8s-config.git
        branch: "#{TAG}"
        auto_update: true
    stages:
    - Test-Stage-2:
        clean_workspace: true
        approval:
          type: success
        jobs:
          Test-Job-2:
            tasks:
            - exec:
                command: echo
                arguments:
                - "Building tag: #{TAG}"
