format_version: 10
pipelines:
  test-pipeline-2:
    group: My-Pipelines
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      test-material-2:
        git: https://github.com/rs-pravingaikwad/argo-java-app-k8s-config.git
        branch: "refs/tags/v1.0.0"
        shallow_clone: false
        auto_update: true
    stages:
    - Test-Stage-2:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          Test-Job-2:
            tasks:
            - exec:
                command: echo            
                arguments:
                - "Using tag: #{TAG}"
    parameters:
      TAG: 'refs/tags/v1.0.0'
