apiVersion: v1
kind: Service
metadata:
  name: argo-java-app-service
spec:
  selector:
    app: argo-java-app 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
