apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
namespace: uat
patchesStrategicMerge:
  - deployment-patch.yaml
resources:
  - uat-config.yaml
images:
  - name: rspgaikwad/argo-java-app
    newName: rspgaikwad/argo-java-app
    newTag: v1.0.0-uat